// Generated by https://quicktype.io

class Detail {
  List<Responsen> detail = new List();

  Detail.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    jsonList.forEach((item) {
      final det = Responsen.fromJsonMap(item);
      detail.add(det);
    });
  }
}

class Responsen {
  int id;
  String materia;
  String titulo;
  String cantidad;
  String fecha;
  String horaini;
  String horafin;
  String plataforma;
  String avance;
  String observacion;
  String foto;

  Responsen({
    this.id,
    this.materia,
    this.titulo,
    this.cantidad,
    this.fecha,
    this.horaini,
    this.horafin,
    this.plataforma,
    this.avance,
    this.observacion,
    this.foto,
  });
  Responsen.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    materia = json['materia'];
    titulo = json['titulo'];
    cantidad = json['cantidad'];
    fecha = json['fecha'];
    horaini = json['horaini'];
    horafin = json['horafin'];
    plataforma = json['plataforma'];
    avance = json['avance'];
    observacion = json['observacion'];
    foto = json['foto'];
  }
}
