// Generated by https://quicktype.io
class Msg {
  int id;
  String nombre;
  String usuario;
  String password;
  String carnet;
  String tipo;
  String email;

  Msg({
    this.id,
    this.nombre,
    this.usuario,
    this.password,
    this.carnet,
    this.tipo,
    this.email,
  });
  //Creamos el Constructor
  Msg.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    nombre = json['nombre'];
    usuario = json['usuario'];
    password = json['password'];
    carnet = json['carnet'];
    tipo = json['tipo'];
    email = json['email'];
  }
}
