// Generated by https://quicktype.io

class Materias {
  List<Request> materias = new List();

  Materias.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    jsonList.forEach((item) {
      final mat = Request.fromJsonMap(item);
      materias.add(mat);
    });
  }
}

class Request {
  int id;
  String materia;
  String sigla;

  Request({
    this.id,
    this.materia,
    this.sigla,
  });

  Request.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    materia = json['materia'];
    sigla = json['sigla'];
  }
}
