// Generated by https://quicktype.io

class Mat {
  List<Request> request;

  Mat({
    this.request,
  });
}

class Request {
  int id;
  String carnet;
  String materia;
  String sigla;

  Request({
    this.id,
    this.carnet,
    this.materia,
    this.sigla,
  });
}
